export const jobsData = [
  {
    id: 1,
    title: "Senior Software Engineer",
    department: "Engineering",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹12,00,000 - ₹15,00,000",
    description:
      "Lead development of custom software solutions for buyers, including web and mobile applications using React, Node.js, and cloud technologies to enhance user experiences and business operations.",
    tags: ["React", "Node.js", "AWS"],
    featured: true,
    postedDays: 2,
    remote: false,
    postedDate: "2 days ago",
    responsibilities: [
      "Design and develop scalable web applications",
      "Collaborate with cross-functional teams",
      "Write clean, maintainable code",
      "Participate in code reviews and mentoring",
    ],
    requirements: [
      "5+ years of software development experience",
      "Strong proficiency in React and Node.js",
      "Experience with cloud platforms (AWS/Azure)",
      "Bachelor's degree in Computer Science or equivalent",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 2,
    title: "Product Designer",
    department: "Design",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹9,00,000 - ₹12,00,000",
    description:
      "Design intuitive user interfaces for our software services, plant marketplace, and safety apps, ensuring seamless experiences for buyers across all platforms.",
    tags: ["Figma", "UX/UI", "Prototyping"],
    featured: false,
    postedDays: 5,
    remote: false,
    postedDate: "5 days ago",
    responsibilities: [
      "Create user-centered designs for web and mobile applications",
      "Conduct user research and usability testing",
      "Develop wireframes, prototypes, and high-fidelity mockups",
      "Collaborate with engineering teams to implement designs",
    ],
    requirements: [
      "3+ years of product design experience",
      "Proficiency in Figma, Sketch, or Adobe Creative Suite",
      "Strong portfolio demonstrating UX/UI skills",
      "Experience with design systems and component libraries",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 3,
    title: "Marketing Manager",
    department: "Marketing",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹10,00,000 - ₹13,00,000",
    description:
      "Manage digital marketing campaigns to promote our software development, plant marketplace, and safety app services to buyers, driving brand awareness and lead generation.",
    tags: ["Digital Marketing", "Analytics", "Strategy"],
    featured: true,
    postedDays: 1,
    remote: false,
    postedDate: "1 day ago",
    responsibilities: [
      "Develop and execute digital marketing strategies",
      "Manage social media campaigns and content creation",
      "Analyze campaign performance and optimize for ROI",
      "Lead a team of marketing professionals",
    ],
    requirements: [
      "4+ years of digital marketing experience",
      "Strong analytical skills and data-driven mindset",
      "Experience with marketing automation tools",
      "Excellent communication and leadership skills",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 4,
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹11,00,000 - ₹14,00,000",
    description:
      "Maintain cloud infrastructure and CI/CD pipelines for our software services, ensuring reliable deployment of applications for buyers in various industries.",
    tags: ["Docker", "Kubernetes", "Terraform"],
    featured: false,
    postedDays: 3,
    remote: false,
    postedDate: "3 days ago",
    responsibilities: [
      "Design and maintain CI/CD pipelines",
      "Manage cloud infrastructure and deployments",
      "Implement monitoring and logging solutions",
      "Ensure system security and compliance",
    ],
    requirements: [
      "3+ years of DevOps experience",
      "Strong knowledge of Docker and Kubernetes",
      "Experience with AWS/Azure cloud platforms",
      "Proficiency in scripting languages (Python, Bash)",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 5,
    title: "Sales Development Representative",
    department: "Sales",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹6,00,000 - ₹8,00,000 + Commission",
    description:
      "Generate qualified leads for our software solutions, digital marketing services, and plant marketplace by prospecting potential buyers and driving revenue.",
    tags: ["B2B Sales", "Lead Generation", "CRM"],
    featured: false,
    postedDays: 7,
    remote: false,
    postedDate: "7 days ago",
    responsibilities: [
      "Research and identify potential customers",
      "Conduct outbound prospecting via phone and email",
      "Qualify leads and schedule demos",
      "Maintain accurate records in CRM system",
    ],
    requirements: [
      "1+ years of sales experience preferred",
      "Strong communication and interpersonal skills",
      "Self-motivated and goal-oriented",
      "Experience with CRM software",
    ],
    benefits: [
      "Competitive base salary plus commission",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 6,
    title: "Data Scientist",
    department: "Engineering",
    location: "Visakhapatnam",
    type: "Full-time",
    salary: "₹13,00,000 - ₹16,00,000",
    description:
      "Analyze data from our software services and plant marketplace to provide insights for buyers, improving product recommendations and safety app functionalities.",
    tags: ["Python", "Machine Learning", "SQL"],
    featured: true,
    postedDays: 4,
    remote: false,
    postedDate: "4 days ago",
    responsibilities: [
      "Develop machine learning models for product recommendations",
      "Analyze user behavior and market trends",
      "Create data visualizations and reports",
      "Collaborate with engineering teams on data infrastructure",
    ],
    requirements: [
      "3+ years of data science experience",
      "Strong proficiency in Python and SQL",
      "Experience with machine learning frameworks",
      "PhD or Master's in relevant field preferred",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
    ],
  },
  {
    id: 7,
    title: "Software Development Intern",
    department: "Engineering",
    location: "Visakhapatnam",
    type: "Internship",
    salary: "₹1,50,000 - ₹2,00,000",
    description:
      "Assist in developing custom software solutions for buyers, gaining hands-on experience with React, Node.js, and cloud technologies in a supportive environment.",
    tags: ["React", "Node.js", "Internship"],
    featured: false,
    postedDays: 1,
    remote: false,
    postedDate: "1 day ago",
    responsibilities: [
      "Assist in developing web applications",
      "Write unit tests and documentation",
      "Participate in code reviews",
      "Learn modern development practices",
    ],
    requirements: [
      "Currently pursuing Computer Science degree",
      "Basic knowledge of React and JavaScript",
      "Strong problem-solving skills",
      "Eagerness to learn and grow",
    ],
    benefits: [
      "Competitive stipend",
      "Mentorship from experienced developers",
      "Flexible work arrangements",
      "Certificate of completion",
    ],
  },
  {
    id: 8,
    title: "Digital Marketing Intern",
    department: "Marketing",
    location: "Visakhapatnam",
    type: "Internship",
    salary: "₹1,20,000 - ₹1,80,000",
    description:
      "Support digital marketing campaigns for our software, plant marketplace, and safety app services, learning analytics and strategy in a dynamic team.",
    tags: ["Digital Marketing", "Analytics", "Internship"],
    featured: false,
    postedDays: 3,
    remote: false,
    postedDate: "3 days ago",
    responsibilities: [
      "Assist in social media content creation",
      "Analyze campaign performance metrics",
      "Support SEO and content marketing efforts",
      "Learn digital marketing tools and platforms",
    ],
    requirements: [
      "Currently pursuing Marketing or Business degree",
      "Basic knowledge of social media platforms",
      "Strong analytical skills",
      "Creative and detail-oriented",
    ],
    benefits: [
      "Competitive stipend",
      "Hands-on experience with real campaigns",
      "Flexible work arrangements",
      "Certificate of completion",
    ],
  },
  {
    id: 9,
    title: "UI/UX Design Intern",
    department: "Design",
    location: "Visakhapatnam",
    type: "Internship",
    salary: "₹1,40,000 - ₹1,90,000",
    description:
      "Work on designing user interfaces for our services, gaining experience with Figma and prototyping to create seamless buyer experiences.",
    tags: ["Figma", "UX/UI", "Internship"],
    featured: false,
    postedDays: 2,
    remote: false,
    postedDate: "2 days ago",
    responsibilities: [
      "Create wireframes and prototypes",
      "Assist in user research and testing",
      "Design user interfaces for web and mobile",
      "Learn design tools and best practices",
    ],
    requirements: [
      "Currently pursuing Design or related degree",
      "Basic knowledge of Figma or design tools",
      "Strong visual design skills",
      "Attention to detail",
    ],
    benefits: [
      "Competitive stipend",
      "Portfolio development opportunities",
      "Flexible work arrangements",
      "Certificate of completion",
    ],
  },
  {
    id: 10,
    title: "Data Analyst Intern",
    department: "Engineering",
    location: "Visakhapatnam",
    type: "Internship",
    salary: "₹1,60,000 - ₹2,20,000",
    description:
      "Analyze data from our software and plant marketplace to provide insights, learning Python and SQL in a real-world setting.",
    tags: ["Python", "SQL", "Internship"],
    featured: false,
    postedDays: 4,
    remote: false,
    postedDate: "4 days ago",
    responsibilities: [
      "Analyze datasets and create reports",
      "Assist in data visualization",
      "Learn SQL queries and data manipulation",
      "Support data science team projects",
    ],
    requirements: [
      "Currently pursuing Data Science or related degree",
      "Basic knowledge of Python or SQL",
      "Strong analytical skills",
      "Attention to detail",
    ],
    benefits: [
      "Competitive stipend",
      "Hands-on data analysis experience",
      "Flexible work arrangements",
      "Certificate of completion",
    ],
  },
];
